# Generated by Django 5.1.6 on 2025-07-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Table Tennis', 'Table Tennis'), ('Running', 'Running')], max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=100)),
                ('total_players', models.PositiveIntegerField()),
                ('event_description', models.TextField(blank=True)),
            ],
        ),
    ]
