# Generated by Django 5.1.6 on 2025-09-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventjoininfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventjoininfo',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='eventjoininfo',
            old_name='mobile_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='eventjoininfo',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-06 00:00:00'),
            preserve_default=False,
        ),
    ]
